spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bokdung2-rds.coootls3xcry.ap-northeast-2.rds.amazonaws.com:3306/bokdung2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bokdung2
    password: bokdung21234!
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  admin-secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-expired-time: 1209600000
  refresh-expired-time: 63200000000
  auth-header: Authorization
  token-type: Bearer
  access-name: ACCESS-TOKEN
  refresh-name: REFRESH-TOKEN

kakao:
  client_id: 2d7c89ba36b0d1de918654da7d9035db
  front_redirect_uri: http://localhost:5173/authcallback
  redirect_uri: http://localhost:8080/api/users/callback/kakao